# Generated by Django 5.0.4 on 2024-05-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='image',
            new_name='imaage',
        ),
    ]
